// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-music.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var search_music_default = defineTool({
  name: "search_music",
  title: "Search music",
  description: "Search the RaagWeather catalog for songs, artists, or albums by keyword.",
  inputSchema: {
    query: z.string().min(1).describe("The search term (song title, artist, or album)."),
    type: z.enum(["track", "artist", "album", "all"]).default("all").describe("Restrict results to a specific entity type."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, type, limit }) => {
    const catalog = [
      { id: "1", title: "Tum Hi Ho", artist: "Arijit Singh", album: "Aashiqui 2", type: "track" },
      { id: "2", title: "Kesariya", artist: "Arijit Singh", album: "Brahmastra", type: "track" },
      { id: "3", title: "Apna Bana Le", artist: "Arijit Singh", album: "Bhediya", type: "track" },
      { id: "4", title: "Raataan Lambiyan", artist: "Jubin Nautiyal", album: "Shershaah", type: "track" },
      { id: "5", title: "Arijit Singh", artist: "Arijit Singh", album: "", type: "artist" },
      { id: "6", title: "AR Rahman", artist: "AR Rahman", album: "", type: "artist" }
    ];
    const q = query.toLowerCase();
    const results = catalog.filter((item) => type === "all" || item.type === type).filter(
      (item) => item.title.toLowerCase().includes(q) || item.artist.toLowerCase().includes(q) || item.album.toLowerCase().includes(q)
    ).slice(0, limit);
    return {
      content: [{ type: "text", text: `Found ${results.length} result(s) for "${query}".` }],
      structuredContent: { results, query, type }
    };
  }
});

// src/lib/mcp/tools/weather-recommendations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var weather_recommendations_default = defineTool2({
  name: "get_weather_recommendations",
  title: "Get weather-based music recommendations",
  description: "Recommend a music playlist tailored to a weather condition (e.g. rainy, sunny, cloudy).",
  inputSchema: {
    weather: z2.enum(["sunny", "rainy", "cloudy", "snowy", "windy", "stormy"]).describe("Current weather condition."),
    mood: z2.enum(["romantic", "energetic", "chill", "devotional", "party", "melancholic"]).nullable().describe("Optional mood filter."),
    language: z2.enum(["hindi", "english", "tamil", "telugu", "punjabi", "marathi"]).default("hindi").describe("Preferred song language.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ weather, mood, language }) => {
    const playlistMap = {
      rainy: {
        name: "Monsoon Melodies",
        vibe: "Soulful ballads for cozy rainy days",
        songs: ["Tum Hi Ho", "Kesariya", "Raataan Lambiyan", "Channa Mereya"]
      },
      sunny: {
        name: "Sunshine Grooves",
        vibe: "Upbeat tracks to match the bright sky",
        songs: ["Kala Chashma", "Badtameez Dil", "Malhari", "Nashe Si Chadh Gayi"]
      },
      cloudy: {
        name: "Overcast Reflections",
        vibe: "Mellow acoustics for a thoughtful day",
        songs: ["Agar Tum Saath Ho", "Phir Le Aya Dil", "Kabira", "Tere Sang Yaara"]
      },
      snowy: {
        name: "Winter Warmth",
        vibe: "Warm classics for chilly evenings",
        songs: ["Perhaps Love", "Jab Koi Baat", "Tum Se Hi", "Pehla Nasha"]
      },
      windy: {
        name: "Free Spirit",
        vibe: "Breezy tracks to match the wind",
        songs: ["Ilahi", "Patakha Guddi", "Zinda", "Yeh Jawaani Hai Deewani"]
      },
      stormy: {
        name: "Thunder & Rhythm",
        vibe: "Intense beats for dramatic weather",
        songs: ["Malhari", "Ghungroo", "Sher Aaya Sher", "Apna Time Aayega"]
      }
    };
    const playlist = playlistMap[weather];
    const moodNote = mood ? ` filtered for a ${mood} mood` : "";
    return {
      content: [
        {
          type: "text",
          text: `Playlist "${playlist.name}" \u2014 ${playlist.vibe}${moodNote}. Language: ${language}. Includes: ${playlist.songs.join(", ")}.`
        }
      ],
      structuredContent: {
        playlist_name: playlist.name,
        vibe: playlist.vibe,
        weather,
        mood,
        language,
        songs: playlist.songs
      }
    };
  }
});

// src/lib/mcp/tools/get-trending.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_trending_default = defineTool3({
  name: "get_trending",
  title: "Get trending songs",
  description: "List trending songs on RaagWeather filtered by region and genre.",
  inputSchema: {
    region: z3.enum(["bollywood", "tollywood", "hollywood", "regional", "global"]).default("bollywood").describe("Region / industry filter."),
    genre: z3.enum(["romantic", "dance", "chill", "devotional", "party", "all"]).default("all").describe("Optional genre filter."),
    limit: z3.number().int().min(1).max(20).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ region, genre, limit }) => {
    const trending = [
      { rank: 1, title: "Kesariya", artist: "Arijit Singh", region: "bollywood", genre: "romantic" },
      { rank: 2, title: "Apna Bana Le", artist: "Arijit Singh", region: "bollywood", genre: "romantic" },
      { rank: 3, title: "Kala Chashma", artist: "Badshah", region: "bollywood", genre: "dance" },
      { rank: 4, title: "Malhari", artist: "Vishal Dadlani", region: "bollywood", genre: "party" },
      { rank: 5, title: "Naatu Naatu", artist: "Rahul Sipligunj", region: "tollywood", genre: "dance" },
      { rank: 6, title: "Blinding Lights", artist: "The Weeknd", region: "hollywood", genre: "dance" },
      { rank: 7, title: "Tum Hi Ho", artist: "Arijit Singh", region: "bollywood", genre: "romantic" },
      { rank: 8, title: "Ghungroo", artist: "Arijit Singh", region: "bollywood", genre: "dance" }
    ];
    const results = trending.filter((s) => region === "global" || s.region === region).filter((s) => genre === "all" || s.genre === genre).slice(0, limit);
    return {
      content: [
        {
          type: "text",
          text: `Top ${results.length} trending ${region} ${genre === "all" ? "" : genre + " "}songs.`
        }
      ],
      structuredContent: { trending: results, region, genre }
    };
  }
});

// src/lib/mcp/tools/create-playlist.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var create_playlist_default = defineTool4({
  name: "create_playlist",
  title: "Create playlist",
  description: "Create a new playlist with a name, description, and initial list of track titles.",
  inputSchema: {
    name: z4.string().min(1).max(80).describe("Playlist name."),
    description: z4.string().max(280).nullable().describe("Optional description."),
    trackTitles: z4.array(z4.string().min(1)).max(50).default([]).describe("Initial track titles to add to the playlist."),
    isPublic: z4.boolean().default(true).describe("Whether the playlist is publicly shareable.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: ({ name, description, trackTitles, isPublic }) => {
    const playlist = {
      id: `pl_${Date.now()}`,
      name,
      description: description ?? "",
      trackTitles,
      trackCount: trackTitles.length,
      isPublic,
      createdAt: (/* @__PURE__ */ new Date()).toISOString()
    };
    return {
      content: [
        {
          type: "text",
          text: `Playlist "${name}" created with ${trackTitles.length} track(s). Visibility: ${isPublic ? "public" : "private"}.`
        }
      ],
      structuredContent: { playlist }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "raagweather-mcp",
  title: "RaagWeather MCP",
  version: "0.1.0",
  instructions: "Tools for RaagWeather \u2014 a weather-driven music streaming app. Use `search_music` to look up songs, artists, or albums; `get_weather_recommendations` to build a playlist tailored to current weather and mood; `get_trending` for the latest charts by region/genre; and `create_playlist` to draft a new playlist. Prefer weather recommendations when the user mentions how they feel or what the sky looks like.",
  tools: [
    search_music_default,
    weather_recommendations_default,
    get_trending_default,
    create_playlist_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
